name: linter-check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        run: |
          make install
      - name: Run linter
        run: |
          make lint